-- Backfill the 3 seeded businesses + Pizza 123 with realistic protocols so the
-- "Protocolo" card on the dashboard is populated for the demo. New businesses
-- onboarded via /onboard get their tasks generated by Opus during provisioning.

do $$
declare
  v_construction uuid;
  v_inventory    uuid;
  v_tiendita     uuid;
  v_pizza        uuid;
begin
  delete from tasks;

  select id into v_construction from businesses where slug = 'villa-nueva';
  select id into v_inventory    from businesses where slug = 'distribuidora-zona-12';
  select id into v_tiendita     from businesses where slug = 'tiendita-zona-7';
  select id into v_pizza        from businesses where slug = 'pizza-123';

  if v_construction is not null then
    insert into tasks (business_id, title, detail, cadence, category) values
      (v_construction, 'Reporte matutino de cuadrilla', 'Don Beto envía mara presente + tareas del día.', 'daily', 'reporte'),
      (v_construction, 'Conciliar facturas con entregas', 'Cruzar facturas físicas con eventos de delivery_in en Capataz.', 'weekly', 'finanzas'),
      (v_construction, 'Revisar avance vs. cronograma', 'Comparar % físico de obra contra plan original.', 'weekly', 'planificacion'),
      (v_construction, 'Inspección de seguridad', 'Verificar EPP, andamios, áreas de riesgo. Reportar incidentes en chat.', 'daily', 'seguridad'),
      (v_construction, 'Pago a proveedores prioritarios', 'Cementos del Valle y Ferretería La Escuadra primero — relación clave.', 'weekly', 'finanzas');
  end if;

  if v_inventory is not null then
    insert into tasks (business_id, title, detail, cadence, category) values
      (v_inventory, 'Conteo cíclico de cemento', 'Validar inventario físico vs. sistema. 30 sacos por muestreo.', 'weekly', 'inventario'),
      (v_inventory, 'Revisar movimientos sin contraparte', 'Cualquier stock_out sin cliente identificado se debe explicar.', 'daily', 'control'),
      (v_inventory, 'Reporte de cobertura colateral', 'Calcular valor mercado / préstamo comprometido para reporte al lender.', 'weekly', 'lender'),
      (v_inventory, 'Limpiar productos lentos', 'Items sin movimiento >30 días → liquidar o devolver.', 'monthly', 'inventario'),
      (v_inventory, 'Validar precios de mercado', 'Llamar 2 proveedores para validar precios spot vs. snapshot interno.', 'weekly', 'precios');
  end if;

  if v_tiendita is not null then
    insert into tasks (business_id, title, detail, cadence, category) values
      (v_tiendita, 'Revisar stock de huevos', 'Si bajan de 60 unidades, pedir al proveedor.', 'daily', 'reabastecer'),
      (v_tiendita, 'Cobrar fiados pendientes', 'Don Chepe, Doña Lucía, vecinos del fondo. Llamar viernes.', 'weekly', 'cuentas'),
      (v_tiendita, 'Verificar productos próximos a vencer', 'Atol shuco, tortillas, lácteos. Rotar primero.', 'daily', 'calidad'),
      (v_tiendita, 'Pago semanal de luz/agua/internet', 'Antes del miércoles para evitar recargo.', 'weekly', 'cuentas'),
      (v_tiendita, 'Limpieza profunda de neveras', 'Sábado en la mañana, antes de abrir.', 'weekly', 'mantenimiento'),
      (v_tiendita, 'Cierre diario de caja', 'Anotar ventas, fiados nuevos, gastos del día.', 'daily', 'cuentas');
  end if;

  if v_pizza is not null then
    insert into tasks (business_id, title, detail, cadence, category) values
      (v_pizza, 'Preparar masa del día', 'Antes de las 9am. Receta base de 5kg de harina.', 'daily', 'cocina'),
      (v_pizza, 'Verificar temperatura del horno', 'Encender 1h antes de abrir. Confirmar 220°C antes del primer pedido.', 'daily', 'equipo'),
      (v_pizza, 'Inventario de toppings', 'Mozzarella, pepperoni, jamón, champiñones. Reabastecer si <2kg.', 'daily', 'inventario'),
      (v_pizza, 'Conciliar pedidos vs. ingreso', 'Comparar lista de pedidos del día contra Q efectivo + transferencias.', 'daily', 'cuentas'),
      (v_pizza, 'Pago al proveedor de queso', 'Pago semanal — relación clave, no fallar.', 'weekly', 'cuentas'),
      (v_pizza, 'Limpieza profunda de horno', 'Domingo, antes del descanso.', 'weekly', 'mantenimiento');
  end if;
end $$;
